#!/bin/bash

# Check to see if running as root

echo -e "\nChecking for root."
if [ `id -u` != 0 ]; then
    echo "Not root."
    echo -e "Need to be run as root.\n"
    echo " Try 'sudo sh before-setup' as a user. Exiting."
    echo ""
    exit 1
else
    echo "Root."
fi

# autologin-pi

# https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=127042
# http://askubuntu.com/questions/679419/how-to-make-auto-login-work-in-ubuntu-no-display-manager
# https://wiki.archlinux.org/index.php/Getty

mkdir -pv /etc/systemd/system/getty@tty1.service.d/
cat <<EOF > /etc/systemd/system/getty@tty1.service.d/autologin.conf
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin pi --noclear %I $TERM
EOF
systemctl enable getty@tty1.service

# Disable IPV6 so that apt or apt-get does not hang when downloading

sysctl -a | grep disable | grep ipv6

# Take result and put 1 instead of zero at end of each row

# Add these lines to /etc/sysctl.conf

#https://wiki.archlinux.org/index.php/sysctl
#From version 207 and 21x, systemd only applies settings from
#/etc/sysctl.d/*.conf and /usr/lib/sysctl.d/*.conf. If you had
#customized /etc/sysctl.conf, you need to rename it as
#/etc/sysctl.d/99-sysctl.conf. If you had e.g. /etc/sysctl.d/foo,
#you need to rename is to /etc/sysctl.d/foo.conf.

# Stop trying for IPV6 as ISP's still use only IPV4 and IPV6 packets are lost
# In case the script was run more than once, cancel previous modification
sed -i 's/ipv6.disable=1 rootwait/rootwait/g' /boot/cmdline.txt
sed -i 's/rootwait/ipv6.disable=1 rootwait/g' /boot/cmdline.txt

# Avoid most of the stuttering of usb sound card because of sdhci-bcm2708 module bugs
# And stuttering dissapears after a few seconds if present because of this
# Better solution should be researched - go to Raspberry Pi 4 ?
# In case the script was run more than once, cancel previous modification
# https://raspberrypi.stackexchange.com/questions/1886/what-kernel-parameters-are-available-for-fixing-usb-problems
# https://www.raspberrypi.org/forums/viewtopic.php?t=12097&start=425

# sed -i 's/sdhci-bcm2708.enable_llm=1 sdhci-bcm2708.sync_after_dma=0 smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0/dwc_otg.lpm_enable=0/g' /boot/cmdline.txt
# sed -i 's/dwc_otg.lpm_enable=0/sdhci-bcm2708.enable_llm=1 sdhci-bcm2708.sync_after_dma=0 smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0/g' /boot/cmdline.txt

# Using 99- to apply after other .conf files enabled ipv6, not needed if cmdline.txt disables IPV6:

# cat <<EOF > /etc/sysctl.d/99-rpi-disable-ipv6.conf
# net.ipv6.conf.all.disable_ipv6 = 1
# net.ipv6.conf.default.disable_ipv6 = 1
# EOF
# net.ipv6.conf.lo.disable_ipv6 = 1
# net.ipv6.conf.eth0.disable_ipv6 = 1
# net.ipv6.conf.[interface].disable_ipv6 = 1

# Disable internal sound card as it's very low quality (check how "Tiesto - Adagio for strings" sounds on it)
# cat <<EOF > /etc/modprobe.d/alsainternalsndoff.conf
# blacklist snd_bcm2835
# EOF
# Disable pulseaudio to reduce sound arterfacts during playback
# https://wiki.archlinux.org/index.php/PulseAudio/Examples
# cat <<EOF > /etc/pulse/client.conf
# autospawn=no
# daemon-binary=/bin/true
# EOF

# Allow usb sound cards to work, avoid alsa errors
# sed -i 's/#options snd-usb-audio index=-2/options snd-usb-audio index=-2/g' /lib/modprobe.d/aliases.conf
# sed -i 's/options snd-usb-audio index=-2/#options snd-usb-audio index=-2/g' /lib/modprobe.d/aliases.conf

# Remove /tmp in tmpfs if already in
sed -i 's/\rtmpfs           \/tmp            tmpfs  nodev,nosuid,mode=1777     0 0//g' /etc/fstab
# and remove multiple newlines (VERY COMPLICATED !!!)
# https://stackoverflow.com/questions/922449/how-can-i-replace-multiple-empty-lines-with-a-single-empty-line-in-bash
sed -i 'N;/^\n$/D;P;D;' /etc/fstab
# Add /tmp in tmpfs in /etc/fstab
echo "" >> /etc/fstab
echo "tmpfs           /tmp            tmpfs  nodev,nosuid,mode=1777     0 0" >> /etc/fstab

# Making sure in case of power loss data loss is reduced drastically

cat <<EOF > /etc/sysctl.d/30-rpi-optimizations.conf
vm.swappiness = 60
vm.min_free_kbytes = 49152
vm.vfs_cache_pressure = 500
vm.dirty_bytes = 8388608
vm.dirty_background_bytes = 8388608
vm.dirty_writeback_centisecs = 600
vm.dirty_expire_centisecs = 600
EOF

# If those files are already there, they get rewritten by ">" , not added to like ">>" does, so no cancelling required.

sync
sleep 2

# Load all configuration files manually:
#sysctl --system

#sysctl -a | grep disable | grep ipv6

# Reboot to completely and utterly disable IPV6, avoiding apt stallings

reboot
