#!/bin/bash

# Song destroyer mode - deletes song when delete button pressed

PLAYERBIN="/usr/bin/omxplayer"
PLAYERTEST="omxplayer"
PLAYERKILL="omxplayer.bin"
PLAYLIST_SAVED_FILE="/root/saved"
SONGFILE=""	# path to the song to be played
START_PLAYER="1"
DETECT_PLAYER="0"
#PATH_MOD="/500gbdate/pi/celtic-dance-by-riverdance-mp3/"
PATH_MOD="/root/music/"
PLAYLIST="/tmp/playlist" # /tmp on Arch is not always a tmpfs so do few writes
PLAYLIST_RECENT_LINE=$[$(cat "$PLAYLIST_SAVED_FILE")]
PLAYLIST_LASTLINE="0"
DELETE_BUTTON_ADRESS="0"
DELETE_BUTTON_RELEASED="1"
NEXT_BUTTON_ADRESS="1"
NEXT_BUTTON_RELEASED="1"

# WiringPi call of GPIO 0 is actually GPIO 17
# WiringPi call of GPIO 1 is actually GPIO 18

# Using gpio command installed when installing WiringPi library, linking it
# http://wiringpi.com/the-gpio-utility/
gpio mode $DELETE_BUTTON_ADRESS in
gpio mode $NEXT_BUTTON_ADRESS in

# Turn off pull down resistors on the two imputs (remains floating, use physical resistors to pull up)
#gpio mode $DELETE_BUTTON_ADRESS tri
#gpio mode $NEXT_BUTTON_ADRESS tri

# Turn on pull up resistors on the two imputs (not as good as using physical 100k resistors)
gpio mode $DELETE_BUTTON_ADRESS up
gpio mode $NEXT_BUTTON_ADRESS up

generate_playlist ()

{

# /tmp on Arch is not always a tmpfs so do few writes (call this rarely)
rm "$PLAYLIST"
find "$PATH_MOD" -iname "*.wav" -exec echo {} >> "$PLAYLIST" \;
find "$PATH_MOD" -iname "*.flac" -exec echo {} >> "$PLAYLIST" \;
find "$PATH_MOD" -iname "*.mp3" -exec echo {} >> "$PLAYLIST" \;
find "$PATH_MOD" -iname "*.ogg" -exec echo {} >> "$PLAYLIST" \;
find "$PATH_MOD" -iname "*.mp4" -exec echo {} >> "$PLAYLIST" \;
#ls -1 "$PATH_MOD" > "$PLAYLIST"
# Detect if music has been found, if not exit
if [ -f "$PLAYLIST" ]
then
	PLAYLIST_LASTLINE=`cat "$PLAYLIST" | wc -l`
else
        espeak -a 600 -p 0 "No songs found, exiting! No songs found, exiting!"
        exit
fi
# Avoid a saved song number larger than the number of songs
if [ "$PLAYLIST_RECENT_LINE" -gt  "$PLAYLIST_LASTLINE" ]
then
PLAYLIST_RECENT_LINE="1"
fi
}


test_player ()

{

	ps -ef | grep -v grep | grep -q $PLAYERTEST
	if [ $? -ne 0 ]
	then
	DETECT_PLAYER="0"
	else
	DETECT_PLAYER="1" 
	fi

}


next_song ()

{

	if [ "$PLAYLIST_RECENT_LINE" -eq  "$PLAYLIST_LASTLINE" ]
	then
	PLAYLIST_RECENT_LINE="1"
	else
	PLAYLIST_RECENT_LINE=$((PLAYLIST_RECENT_LINE+1))
	fi
	# Will write changes to disk just before starting the player
	START_PLAYER="1"
	# Save playlist position
	echo "$PLAYLIST_RECENT_LINE" > "$PLAYLIST_SAVED_FILE"

}


delete_song ()

{

	espeak -a 600 -p 0 "Deleted."
	/usr/bin/sleep 0.1
	rm "$SONGFILE"
	# http://www.yourownlinux.com/2015/04/sed-command-in-linux-delete-lines-from-file.html
	# http://stackoverflow.com/questions/5171901/sed-command-find-and-replace-in-file-and-overwrite-file-doesnt-work-it-empties
	sed -i "$PLAYLIST_RECENT_LINE d" $PLAYLIST
	# Decrease song number by one so that next_song will use the same song number
	if [ "$PLAYLIST_RECENT_LINE" -eq  "1" ]
	then
	PLAYLIST_RECENT_LINE="$PLAYLIST_LASTLINE"
	else
	PLAYLIST_RECENT_LINE=$((PLAYLIST_RECENT_LINE-1))
	fi

}


#### [ BOOTING WITH SYSTEMD ] ####

# Lite boot delay (no x server)
/usr/bin/sleep 3

# Heavy boot delay (x server)
#/usr/bin/sleep 5

# Check four times (detect possible unwanted noise) that pull up resistors for buttons work, exit if not
if [ `gpio read $DELETE_BUTTON_ADDRESS` = 0  ] || [ `gpio read $NEXT_BUTTON_ADRESS` = 0 ]
then
	/usr/bin/sleep 0.1
	if [ `gpio read $DELETE_BUTTON_ADDRESS` = 0 ] || [ `gpio read $NEXT_BUTTON_ADRESS` = 0 ]
	then
		/usr/bin/sleep 0.1
		if [ `gpio read $DELETE_BUTTON_ADDRESS` = 0 ] || [ `gpio read $NEXT_BUTTON_ADRESS` = 0 ]
		then
			/usr/bin/sleep 0.1
			if [ `gpio read $DELETE_BUTTON_ADDRESS` = 0 ] || [ `gpio read $NEXT_BUTTON_ADRESS` = 0 ]
			then
				espeak -a 600 -p 0 "Buttons pull uo resistors not working properly, exiting."
				/usr/bin/sleep 0.1
				espeak -a 600 -p 0 "Buttons pull uo resistors not working properly, exiting."
			exit
			fi
		fi
	fi
fi

#### [ INCREASE BATTERY LIFE FOR B MODEL, THIS DISABLES USB AND LAN CHIP ] ####

#echo 0x0 > /sys/devices/platform/bcm2708_usb/buspower

#### [ PLAYLIST ] ####

# Uncomment if using a USB stick or card in USB adapter
#mount /dev/sda1 /root/music

# This will also be called after a song delete
generate_playlist

# Only once at start specify status
espeak -a 600 -p 0 "Found $PLAYLIST_LASTLINE songs, playing $PLAYLIST_RECENT_LINE."

#### [ SYNC DATA TO PROTECT AGAINST CORRUPTION FROM POWER LOSS ] ####

# This is saving all changes done to disk by the systemd boot process
#/usr/bin/sleep 0.1
#sync
#/usr/bin/sleep 0.1

#### [ CONTROL LOOP THAT REPEATS INFINETLY ] ####

while true
do

## [ START THE PLAYER ] ##

	if [ $START_PLAYER -eq "1" ]
	then
	# Determine the song by wanted line in the playlist (path and filename)
	SONGFILE=`cat "$PLAYLIST" | sed -n "$PLAYLIST_RECENT_LINE"p`
	# Write all changes to disk (before starting the player)
	/usr/bin/sleep 0.1
	sync
	/usr/bin/sleep 0.1
	# Starting the player, when " &" at the end, the script continues without waiting to finish command to the left
	"$PLAYERBIN" --vol -1000 "$SONGFILE" &
	# --vol -1000 reduces volume to aproximately 90%, required for bass not to go over in sound adapter
	fi

## [ DETECT DELETE BUTTON RELEASED ---->>>> ALLOW A NEW DELETE BUTTON TO BE PRESSED ] ##

	if [ `gpio read $DELETE_BUTTON_ADRESS` = 1 ]
	then
	# Wait for the GPIO driver to rest
	/usr/bin/sleep 0.1
	# Test again to make sure it is not noise
		if [ `gpio read $DELETE_BUTTON_ADRESS` = 1 ]
		then
		# Wait for the GPIO driver to rest
		/usr/bin/sleep 0.1
		DELETE_BUTTON_RELEASED="1"
		fi
	fi

## [ DETECT DELETE BUTTON WAS RELEASED AND IS PRESSED ---->>>  STOP PLAYER  ---->>>>  DELETE THE UNWANTED SONG ] ##

	if [ $DELETE_BUTTON_RELEASED -eq "1" ] && [ `gpio read $DELETE_BUTTON_ADRESS` = 0 ]
	then
	# Wait for the GPIO driver to rest
	/usr/bin/sleep 0.1
	# Test again to make sure it is not noise (already checked released)
		if [ `gpio read $DELETE_BUTTON_ADRESS` = 0 ]
		then
		# Wait for the GPIO driver to rest
		/usr/bin/sleep 0.1
		# Killing the player like a song ending will allow a next song
		killall $PLAYERKILL
		# Deleting song after the player is not playing it
		# Wait for the file system to be released after the player has been killed
		/usr/bin/sleep 0.1
		delete_song
		# Wait for the file system to acknowledge the deletion
		/usr/bin/sleep 0.1
		# Don't allow a new delete button press until released
		DELETE_BUTTON_RELEASED="0"
		fi
	fi

## [ DETECT NEXT BUTTON RELEASED ---->>>> ALLOW A NEW NEXT BUTTON TO BE PRESSED ] ##

	if [ `gpio read $NEXT_BUTTON_ADRESS` = 1 ]
	then
	# Wait for the GPIO driver to rest
	/usr/bin/sleep 0.1
	# Test again to make sure it is not noise
		if [ `gpio read $NEXT_BUTTON_ADRESS` = 1 ]
		then
		# Wait for the GPIO driver to rest
		/usr/bin/sleep 0.1
		NEXT_BUTTON_RELEASED="1"
		fi
	fi

## [ DETECT NEXT BUTTON WAS RELEASED AND IS PRESSED ---->>>  STOP PLAYER  ---->>>>  CURRENT SONG FINISHED SO NEXT ] ##

	if [ $NEXT_BUTTON_RELEASED -eq "1" ] && [ `gpio read $NEXT_BUTTON_ADRESS` = 0 ]
	then
	# Wait for the GPIO driver to rest
	/usr/bin/sleep 0.1
	# Test again to make sure it is not noise (already checked released)
		if [ `gpio read $NEXT_BUTTON_ADRESS` = 0 ]
		then
		# Wait for the GPIO driver to rest
		/usr/bin/sleep 0.1
		# Killing the player like a song ending will allow a next song
		killall $PLAYERKILL
		# Wait for the file system to be released after the player has been killed
		/usr/bin/sleep 0.1
		espeak -a 600 -p 0 "Next."
		/usr/bin/sleep 0.1
		# Don't allow a new next button press until released
		NEXT_BUTTON_RELEASED="0"
		fi
	fi

## [ DETECT PLAYER STOPPED (song end/next or killed by delete) ---->>>>  NEXT SONG ] ##

	test_player
	if [ $DETECT_PLAYER -eq "0" ]
	then
	next_song
	else
	# Avoid if START_PLAYER="1" to be faster, repeatedly zero
	START_PLAYER="0"
	fi

## [ GO SLOWER THROUGH THE INFINITE LOOP IF NO CHANGES ] ##

	# But be fast enough to sense the buttons and stopped player with snapiness
	/usr/bin/sleep 0.1

done
