#!/bin/bash
espeak-ng -a 400 -p 0 -w 01x.wav "This is song number 1, number 1, number 1, number 1, number 1, number 1, number 1, number 1, number 1, number 1, lala lala. Yes indeed. Aha aha."
espeak-ng -a 400 -p 0 -w 02x.wav "This is song number 2, number 2, number 2, number 2, number 2, number 2, number 2, number 2, number 2, number 2, lala lala. Yes indeed. Aha aha."
espeak-ng -a 400 -p 0 -w 03x.wav "This is song number 3, number 3, number 3, number 3, number 3, number 3, number 3, number 3, number 3, number 3, lala lala. Yes indeed. Aha aha."
espeak-ng -a 400 -p 0 -w 04x.wav "This is song number 4, number 4, number 4, number 4, number 4, number 4, number 4, number 4, number 4, number 4, lala lala. Yes indeed. Aha aha."
espeak-ng -a 400 -p 0 -w 05x.wav "This is song number 5, number 5, number 5, number 5, number 5, number 5, number 5, number 5, number 5, number 5, lala lala. Yes indeed. Aha aha."
espeak-ng -a 400 -p 0 -w 06x.wav "This is song number 6, number 6, number 6, number 6, number 6, number 6, number 6, number 6, number 6, number 6, lala lala. Yes indeed. Aha aha."
espeak-ng -a 400 -p 0 -w 07x.wav "This is song number 7, number 7, number 7, number 7, number 7, number 7, number 7, number 7, number 7, number 7, lala lala. Yes indeed. Aha aha."
espeak-ng -a 400 -p 0 -w 08x.wav "This is song number 8, number 8, number 8, number 8, number 8, number 8, number 8, number 8, number 8, number 8, lala lala. Yes indeed. Aha aha."
espeak-ng -a 400 -p 0 -w 09x.wav "This is song number 9, number 9, number 9, number 9, number 9, number 9, number 9, number 9, number 9, number 9, lala lala. Yes indeed. Aha aha."
sync
