#!/bin/bash
### Prepare a fresh Arch Linux ARM install, which uses less card space.
### Edit /boot/config.txt for sound over HDMI and/or removing white noise, if you want a DVI monitor to
### work you need to have analog sound over the 3,5 mm jack by setting hdmi_drive=1 and commenting with
### a "#" hdmi_force_edid_audio=1 and before that you need to set a resolution, I use 1280 x 1024 @ 60Hz:
####### hdmi_group=2
####### hdmi_mode=35
####### hdmi_drive=2
####### hdmi_force_edid_audio=1
####### hdmi_force_hotplug=1
####### disable_audio_dither=1
### Install programs required by bshplyr-next on Arch Linux ARM after it has Internet acces:
### alsa-utils - use "speaker-test" to test speakers or "alsamixer" to set volume for other players
### psmisc - use "killall" to kill the player or bshplyr-next
### wiringpi - use "gpio" to sense pressing the delete button
### This are the commands to install them:
pacman -Syu
pacman -S alsa-utils psmisc wiringpi omxplayer
### Create files and folders:
echo "1" > /root/saved
echo "Next:" > /root/nextpressed
# /root/music must contain music or movie files and no folders
mkdir /root/music
# The playlist is done at each boot by the script and the last song is remembered
cp bshplyr-next /usr/bin
cp bshplyr-next.service /etc/systemd/system/multi-user.target.wants
chmod 777 /usr/bin/bshplyr-next
chmod 777 /etc/systemd/system/multi-user.target.wants/bshplyr-next.service
# Move systemd-networkd.service and systemd-resolved.service to another folder to disable network
##################################################################################
# Take sdhc card to abother computer, sudo copy music to mounted /root/music, put back in your
# Raspberry PI and only plug your stereo headphone/speaker jack and power, with at least
# GPIO pin 17 ready to pull to 3.3v with 10kohm for shutting down safely
# To be portable use a laptop battery witch provides at least a day autonomy through a GPS car charger
# to power the Raspberry Pi and disable USB/LAN chip (uncomment battery section in bshplyr for model B).
