#!/bin/bash
### Prepare a fresh Raspbian Lite install, which uses less card space.
### Edit /boot/config.txt for sound over HDMI and/or removing white noise, if you want a DVI monitor to
### work you need to have analog sound over the 3,5 mm jack by setting hdmi_drive=1 and commenting with
### a "#" hdmi_force_edid_audio=1 and before that you need to set a resolution, I use 1280 x 1024 @ 60Hz:
####### hdmi_group=2
####### hdmi_mode=35
####### hdmi_drive=2
####### hdmi_force_edid_audio=1
####### hdmi_force_hotplug=1
####### disable_audio_dither=1
### Install programs required by bshplyr-delete on Arch Linux ARM after it has Internet acces:
### alsa-utils - use "speaker-test" to test speakers or "alsamixer" to set volume for other players
### psmisc - use "killall" to kill the player or bshplyr-delete - in Raspbian needs other expression than in Arch
### wiringpi - use "gpio" to sense pressing the delete button
### espeak - use "espeak" to report that the song is deleted
### omxplayer - accelerated decoding libraries, video
### mpv - very good as audio player on a low resources board
### This are the commands to install them:
apt-get update
apt-get install -y alsa-utils psmisc espeak mpv
### Create files and folders:
echo "1" > /root/saved
#echo "Next:" > /root/nextpressed
# /root/music must contain music or movie files in folders or no folders
mkdir /root/music
# The playlist is done at each boot by the script and the last song is remembered
cp bshplyr-delete-raspbian-lite /usr/bin
cp bshplyr-delete-raspbian-lite.service /etc/systemd/system/multi-user.target.wants
chmod 775 /usr/bin/bshplyr-delete-raspbian-lite
chmod 775 /etc/systemd/system/multi-user.target.wants/bshplyr-delete-raspbian-lite.service
# Move systemd-networkd.service and systemd-resolved.service to another folder to disable network
##################################################################################
# Take sdhc card to abother computer, sudo copy music to mounted /root/music, put back in your
# Raspberry PI and only plug your stereo headphone/speaker jack and power, with at least
# GPIO pin 17 ready to pull to 3.3v with 10kohm for shutting down safely
# To be portable use a laptop battery witch provides at least a day autonomy through a GPS car charger
# to power the Raspberry Pi and disable USB/LAN chip (uncomment battery section in bshplyr for model B).
